owner: airplanes-live
repo: status

sites:
  - name: airplanes.live
    url: https://airplanes.live
  - name: globe.airplanes.live
    url: https://globe.airplanes.live
  - name: maps.airplanes.live
    url: https://maps.airplanes.live
  - name: api.airplanes.live
    url: https://api.airplanes.live/status
  - name: BEAST Ingest
    url: feed.airplanes.live
    check: tcp-ping
    port: 30004
  - name: MLAT Ingest
    url: feed.airplanes.live
    check: tcp-ping
    port: 31090

status-website:
  cname: status.airplanes.live
  logoUrl: https://raw.githubusercontent.com/airplanes-live/status/master/assets/icon.svg
  name: Upptime
  introTitle: "Airplanes.live Status"
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/airplanes-live/status