# Change these first
owner: airplanes-live # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: airplanes.live
    url: https://airplanes.live
  - name: globe.airplanes.live
    url: https://globe.airplanes.live
  - name: maps.airplanes.live
    url: https://maps.airplanes.live
  - name: api.airplanes.live
    url: https://api.airplanes.live/status
  - name: feed.airplanes.live:30004
    url: feed.airplanes.live
    check: tcp-ping
    port: 30004
  - name: feed.airplanes.live:31090
    url: feed.airplanes.live
    check: tcp-ping
    port: 31090

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.airplanes.live
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Airplanes.live Status"
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/airplanes-live/status

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration